In [38]:
import pandas as pd
df=pd.read_csv('car data.csv')
df.drop(columns=['Car_Name'],inplace=True)
df

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [39]:
df=pd.get_dummies(df,columns=['Fuel_Type'],drop_first=True)
df

,Year,Selling_Price,Present_Price,Kms_Driven,Seller_Type,Transmission,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol
0,2014,3.35,5.59,27000,Dealer,Manual,0,False,True
1,2013,4.75,9.54,43000,Dealer,Manual,0,True,False
2,2017,7.25,9.85,6900,Dealer,Manual,0,False,True
3,2011,2.85,4.15,5200,Dealer,Manual,0,False,True
4,2014,4.60,6.87,42450,Dealer,Manual,0,True,False
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Dealer,Manual,0,True,False
297,2015,4.00,5.90,60000,Dealer,Manual,0,False,True
298,2009,3.35,11.00,87934,Dealer,Manual,0,False,True
299,2017,11.50,12.50,9000,Dealer,Manual,0,True,False
300,2016,5.30,5.90,5464,Dealer,Manual,0,False,True

In [40]:
df=pd.get_dummies(df,columns=['Transmission'],drop_first=True)
df

,Year,Selling_Price,Present_Price,Kms_Driven,Seller_Type,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Transmission_Manual
0,2014,3.35,5.59,27000,Dealer,0,False,True,True
1,2013,4.75,9.54,43000,Dealer,0,True,False,True
2,2017,7.25,9.85,6900,Dealer,0,False,True,True
3,2011,2.85,4.15,5200,Dealer,0,False,True,True
4,2014,4.60,6.87,42450,Dealer,0,True,False,True
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,Dealer,0,True,False,True
297,2015,4.00,5.90,60000,Dealer,0,False,True,True
298,2009,3.35,11.00,87934,Dealer,0,False,True,True
299,2017,11.50,12.50,9000,Dealer,0,True,False,True
300,2016,5.30,5.90,5464,Dealer,0,False,True,True

# Where Function

In [41]:
import numpy as np
df=pd.DataFrame({'Marks':[40,35,65,31,70,95,18]})
df['Result']=np.where(df['Marks']>40 , 'Pass', 'Fail')
df

   Marks Result
0     40   Fail
1     35   Fail
2     65   Pass
3     31   Fail
4     70   Pass
5     95   Pass
6     18   Fail

In [42]:
df=pd.DataFrame({'Marks':[40,35,65,31,70,95,18]})
df['Grade']=np.where(df['Marks']>75,'A',np.where(df['Marks']>50,'B','C'))
df

   Marks Grade
0     40     C
1     35     C
2     65     B
3     31     C
4     70     B
5     95     A
6     18     C

# Mathemetical Operation

In [43]:
df=pd.DataFrame({'Math':[45,60,75],'Science':[50,60,70]})
df['Total']=df['Math']+df['Science']
df['Average']=df['Total']/2
df

   Math  Science  Total  Average
0    45       50     95     47.5
1    60       60    120     60.0
2    75       70    145     72.5

# Test_Train_Split

In [44]:
from sklearn.model_selection import train_test_split
df=pd.read_csv('car data.csv')
df.drop(columns=['Car_Name'],inplace=True)
df=pd.get_dummies(df,drop_first=True)
df

,Year,Selling_Price,Present_Price,Kms_Driven,Owner,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,2014,3.35,5.59,27000,0,False,True,False,True
1,2013,4.75,9.54,43000,0,True,False,False,True
2,2017,7.25,9.85,6900,0,False,True,False,True
3,2011,2.85,4.15,5200,0,False,True,False,True
4,2014,4.60,6.87,42450,0,True,False,False,True
...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,True,False,False,True
297,2015,4.00,5.90,60000,0,False,True,False,True
298,2009,3.35,11.00,87934,0,False,True,False,True
299,2017,11.50,12.50,9000,0,True,False,False,True
300,2016,5.30,5.90,5464,0,False,True,False,True

In [45]:
# y=mx+c
y=df['Selling_Price']
x=df.drop(columns=['Selling_Price'])
x,y

(     Year  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
 0    2014           5.59       27000      0             False
 1    2013           9.54       43000      0              True
 2    2017           9.85        6900      0             False
 3    2011           4.15        5200      0             False
 4    2014           6.87       42450      0              True
 ..    ...            ...         ...    ...               ...
 296  2016          11.60       33988      0              True
 297  2015           5.90       60000      0             False
 298  2009          11.00       87934      0             False
 299  2017          12.50        9000      0              True
 300  2016           5.90        5464      0             False

      Fuel_Type_Petrol  Seller_Type_Individual  Transmission_Manual
 0                True                   False                 True
 1               False                   False                 True
 2                True                   False                 True
 3                True                   False                 True
 4               False                   False                 True
 ..                ...                     ...                  ...
 296             False                   False                 True
 297              True                   False                 True
 298              True                   False                 True
 299             False                   False                 True
 300              True                   False                 True

 [301 rows x 8 columns],
 0       3.35
 1       4.75
 2       7.25
 3       2.85
 4       4.60
        ...
 296     9.50
 297     4.00
 298     3.35
 299    11.50
 300     5.30
 Name: Selling_Price, Length: 301, dtype: float64)

In [46]:
print(x.shape)
print(y.shape)

(301, 8)
(301,)

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
print('x : ',x_train.shape,x_test.shape)
print('y : ',y_train.shape,y_test.shape)

x :  (240, 8) (61, 8)
y :  (240,) (61,)

In [36]:
print(x_test)
print(y_test)

     Year  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
177  2016           0.57       24000      0             False
289  2016          13.60       10980      0             False
228  2012           9.40       60000      0              True
198  2011           0.57       35000      1             False
60   2013          18.61       40001      0             False
..    ...            ...         ...    ...               ...
234  2015           5.70        4492      0             False
296  2016          11.60       33988      0              True
281  2006           7.60       50456      0             False
285  2016           8.50       15059      0             False
182  2013           0.58       30000      0             False

     Fuel_Type_Petrol  Seller_Type_Individual  Transmission_Manual
177              True                    True                False
289              True                   False                 True
228             False                   False                 True
198              True                    True                 True
60               True                   False                 True
..                ...                     ...                  ...
234              True                   False                 True
296             False                   False                 True
281              True                   False                 True
285              True                   False                False
182              True                    True                 True

[61 rows x 8 columns]
177     0.35
289    10.11
228     4.95
198     0.15
60      6.95
       ...
234     5.50
296     9.50
281     2.10
285     7.40
182     0.30
Name: Selling_Price, Length: 61, dtype: float64